//
//  FlagNameConverter.swift
//  Football Guru
//
//  Created by Dave Bage on 30/10/2021.
//

import Foundation
import SwiftUI

class FlagNameConverter {
    
    enum SearchType {
        case player
        case team
    }
    
    let playersFlagsDictionary = [
        "Afghan" : "afghanistan",
        "Albanian" : "albania",
        "Algerian" : "algeria",
        "American" : "united_states",
        "American Samoan" : "american_Samoa",
        "Andorran" : "andorra",
        "Angolan" : "angola",
        "Anguillan" : "anguilla",
        "Antiguan" : "antigua_and_barbuda",
        "Argentine" : "argentina",
        "Armenian" : "armenia",
        "Aruban" : "aruba",
        "Australian" : "australia",
        "Austrian" : "austria",
        "Azerbaijani" : "azerbaijan",
        "Bahamian" : "bahamas",
        "Bahraini" : "bahrain",
        "Bangladeshi" : "bangladesh",
        "Barbadian" : "barbados",
        "Basotho" : "lesotho",
        "Belarusian" : "belarus",
        "Belgian" : "belgium",
        "Belizean" : "belize",
        "Beninese" : "benin",
        "Bermudian" : "bermuda",
        "Bhutanese" : "bhutan",
        "Bolivian" : "bolivia",
        "Bosnian" : "bosnia_and_herzegovina",
        "Botswanan" : "botswana",
        "Brazilian" : "brazil",
        "British Virgin Islander" : "british_virgin_islands",
        "Bruneian" : "brunei",
        "Bulgarian" : "bulgaria",
        "Burkinabe" : "burkina_Faso",
        "Burmese" : "myanmar",
        "Burundian" : "burundi",
        "Cambodian" : "cambodia",
        "Cameroonian" : "cameroon",
        "Canadian" : "canada",
        "Cape Verdean" : "cape_verde",
        "Caymanian" : "cayman_islands",
        "Central African" : "central_african_republic",
        "Chadian" : "chad",
        "Chilean" : "chile",
        "Chinese" : "china",
        "Colombian" : "colombia",
        "Comoran" : "comoros",
        "Congolese" : "republic_of_the_congo",
        "Congolese (DRC)" : "democratic_republic_of_the_congo",
        "Cook Islander" : "cook_islands",
        "Costa Rican" : "costa_rica",
        "Croatian" : "croatia",
        "Cuban" : "cuba",
        "Curaçaoan" : "curacao",
        "Cypriot" : "cyprus",
        "Czech" : "czech_republic",
        "Danish" : "denmark",
        "Djiboutian" : "djibouti",
        "Dominican" : "dominica",
        "Dominican Republic" : "dominican_republic",
        "Dutch" : "netherlands",
        "Ecuadorian" : "ecuador",
        "Egyptian" : "egypt",
        "Emirati" : "united_arab_emirates",
        "English" : "england",
        "Equatoguinean" : "equatorial_guinea",
        "Eritrean" : "eritrea",
        "Estonian" : "estonia",
        "Ethiopian" : "ethiopia",
        "Faroese" : "faroes",
        "Fijian" : "fiji",
        "Finnish" : "finland",
        "French" : "france",
        "Gabonese" : "gabon",
        "Gambian" : "gambia",
        "Georgian" : "georgia",
        "German" : "germany",
        "Ghanaian" : "ghana",
        "Gibraltarian" : "gibraltar",
        "Greek" : "greece",
        "Grenadian" : "grenada",
        "Guamanian" : "guam",
        "Guatemalan" : "guatemala",
        "Guinean" : "guinea",
        "Guinean (Bissau)" : "guinea_bissau",
        "Guyanese" : "guyana",
        "Haitian" : "haiti",
        "Honduran" : "honduras",
        "Hong Kong" : "hong_kong",
        "Hungarian" : "hungary",
        "Icelandic" : "iceland",
        "Indian" : "india",
        "Indonesian" : "indonesia",
        "Iranian" : "iran",
        "Iraqi" : "iraq",
        "Irish" : "ireland",
        "Israeli" : "israel",
        "Italian" : "italy",
        "Ivorian" : "cote_divoire",
        "Jamaican" : "jamaica",
        "Japanese" : "japan",
        "Jordanian" : "jordan",
        "Kazakhstani" : "kazakhstan",
        "Kenyan" : "kenya",
        //"kiribatien" :
        "Kittitian" : "saint_kitts_and_nevis",
        "Kosovar" : "kosovo",
        "Kuwaiti" : "kuwait",
        "Kyrgyzstani" : "kyrgyzstan",
        "Laotian" : "laos",
        "Latvian" : "latvia",
        "Lebanese" : "lebanon",
        "Liberian" : "liberia",
        "Libyan" : "libya",
        "Liechtenstein" : "liechtenstein",
        "Lithuanian" : "lithuania",
        "Macanese" : "macau",
        "Macedonian" : "macedonia",
        "Mahoran" : "mayotte",
        "Malagasy" : "madagascar",
        "Malawian" : "malawi",
        "Malaysian" : "malaysia",
        "Maldivian" : "maldives",
        "Malian" : "mali",
        "Maltese" : "malta",
        "Martiniquais" : "martinique",
        "Mauritanian" : "mauritania",
        "Mauritian" : "mauritius",
        "Mexican" : "mexico",
        "Moldovan" : "moldova",
        "Mongolian" : "mongolia",
        "Montenegrin" : "montenegro",
        "Montserratian" : "montserrat",
        "Moroccan" : "morocco",
        "Mozambican" : "mozambique",
        "Namibian" : "namibia",
        "Nepali" : "nepal",
        "New Caledonian" : "new_caledonia",
        "New Zealand" : "new_zealand",
        "Ni_Vanuatu" : "vanuatu",
        "Nicaraguan" : "nicaragua",
        "Nigerian" : "nigeria",
        "Nigerien" : "niger",
        "North Korean" : "north_korea",
        "Northern Irish" : "northern_ireland",
        "Norwegian" : "norway",
        "Omani" : "oman",
        "Pakistani" : "pakistan",
        "Palestinian" : "palestine",
        "Panamanian" : "panama",
        "Papua New Guinean" : "papua_new_guinea",
        "Paraguayan" : "paraguay",
        "Peruvian" : "peru",
        "Philippine" : "philippines",
        "Polish" : "poland",
        "Portuguese" : "portugal",
        "Puerto Rican" : "puerto_rico",
        "Qatari" : "qatar",
        "Réunionese" : "france",
        "Romanian" : "romania",
        "Rwandan" : "rwanda",
        "Russian" : "russia",
        "Saint Lucian" : "saint_lucia",
        "Salvadoran" : "el_salvador",
        "Sammarinese" : "san_marino",
        "São Toméan" : "sao_tome_and_principe",
        "Saudi" : "saudi_arabia",
        "Samoan" : "samoa",
        "Scottish" : "scotland",
        "Senegalese" : "senegal",
        "Serbian" : "serbia",
        "Seychellois" : "seychelles",
        "Sierra Leonean" : "sierra_leone",
        "Singaporean" : "singapore",
        "Slovak" : "slovakia",
        "Slovenian" : "slovenia",
        "Solomon Island" : "solomon_islands",
        "Somali" : "Somalia",
        "South African" : "south_africa",
        "South Korean" : "south_korea",
        "South Sudanese" : "south_sudan",
        "Spanish" : "spain",
        "Sudanese" : "sudan",
        "St. Vincentian" : "saint_vincent_and_the_grenadines",
        "Surinamese" : "suriname",
        "Swazi" : "swaziland",
        "Swedish" : "sweden",
        "Swiss" : "switzerland",
        "Syrian" : "syria",
        "Tahitian" : "tahiti",
        "Taiwanese" : "taiwan",
        "Tajikistani" : "tajikistan",
        "Tanzanian" : "tanzania",
        "Thai" : "thailand",
        "Timorese" : "east_timor",
        "Togolese" : "togo",
        "Tongan" : "tonga",
        "Trinidadian" : "trinidad_and_tobago",
        "Tunisian" : "tunisia",
        "Turkish" : "turkey",
        "Turkmen" : "turkmenistan",
        "Turks and Caicos" : "turks_and_caicos_islands",
        "Ugandan" : "uganda",
        "Ukrainian" : "ukraine",
        "Uruguayan" : "uruguay",
        "US Virgin Islander" : "us_virgin_islands",
        "Uzbekistani" : "uzbekistan",
        "Venezuelan" : "venezuela",
        "Vietnamese" : "vietnam",
        "Welsh" : "wales",
        "Yemeni" : "yemen",
        "Zambian" : "zambia",
        "Zimbabwean" : "zimbabwe"]
    
    let teamsFlagsDictionary = [
        "American Samoa" : "american_samoa",
        "Antigua and Barbuda" : "antigua_and_barbuda",
        "Aruba" : "aruba",
        "Basque Country" : "basque_country",
        "Belgium" : "belgium",
        "Bolivia" : "bolivia",
        "Bosnia and Herzegovina" : "bosnia_and_herzegovina",
        "Burkina Faso" : "burkina_faso",
        "Canary Islands" : "canary_islands",
        "Cayman Islands" : "cayman_islands",
        "Cape Verde" : "cape_verde",
        "Central African R" : "central_african_republic",
        "Chinese Taipei" : "taiwan",
        "Congo" : "democratic_republic_of_the_congo",
        "Costa Rica" : "costa_rica",
        "Curaçao" : "curacao",
        "Czech Republic" : "czech_republic",
        "Dominican Republic" : "dominican_republic",
        "DR Congo" : "democratic_republic_of_the_congo",
        "East Timor" : "east_timor",
        "El Salvador" : "el_salvador",
        "England" : "england",
        "Equatorial Guinea" : "equatorial_guinea",
        "Faroe Islands" : "faroes",
        "France" : "france",
        "French Guiana" : "french_guiana",
        "Hong Kong" : "hong_kong",
        "Ireland" : "ireland",
        "Ivory Coast" : "cote_divoire",
        "Germany" : "germany",
        "Martinica" : "martinique",
        "Mexico" : "mexico",
        "Netherlands Antilles" : "netherlands_antilles",
        "New Caledonia" : "new_caledonia",
        "New Zealand" : "new_zealand",
        "North Korea" : "north_korea",
        "Northern Cyprus" : "northern_cyprus",
        "Northern Ireland" : "northern_ireland",
        "Northern Mariana" : "northern_mariana_islands",
        "Papua New Guinea" : "papua_new_guinea",
        "Puerto Rico" : "puerto_rico",
        "Republic of Ireland" : "ireland",
        "Réunion" : "france",
        "Saint Lucia" : "saint_lucia",
        "Saint Kitts and Nevis" : "saint_kitts_and_nevis",
        "Saint Vincent" : "saint_vincent_and_the_grenadines",
        "San Marino" : "san_marino",
        "São Tomé and Príncipe" : "sao_tome_and_principe",
        "Saudi Arabia" : "saudi_arabia",
        "Sierra Leone" : "sierra_leone",
        "Solomon Islands" : "solomon_islands",
        "South Africa" : "south_africa",
        "South Korea" : "south_korea",
        //"South Yemen" : "",
        "Sri Lanka" : "sri_lanka",
        "Tibet" : "China",
        "Trinidad and Tobago" : "trinidad_and_tobago",
        "Turks & Caicos Islands" : "turks_and_caicos_islands",
        "United Arab Emirates" : "united_arab_emirates",
        "United States" : "united_states",
        "Wallis & Futuna" : "wallis_and_futuna",
        "Zanzibar" : "tanzania"
    ]
    
    func flagImage(nationality: String, searchType: SearchType) -> Image? {
        if searchType == .team, let flagImageName = teamsFlagsDictionary[nationality] {
            return Image(flagImageName)
        } else if searchType == .player, let flagImageName = playersFlagsDictionary[nationality] {
            return Image(flagImageName)
        }
        return nil
    }
}
